#! /bin/sh

sxhkd &
setxkbmap -layout "us,ru" -option "grp:caps_toggle,compose:menu"
nm-applet &
pnmixer &
xcompmgr &
nitrogen --restore &
polybar example &

bspc monitor  -d I II III IV V VI VII VIII IX X

bspc config border_width           2
bspc config window_gap             3

bspc config split_ratio            0.50
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config focus_follows_pointer  true

bspc config normal_border_color    "#44475a"
bspc config active_border_color    "#bd93f9"
bspc config focused_border_color   "#ff79c6"
bspc config presel_feedback_color  "#6272a4"

